"""
Stage 5 — Code Skeleton Generator
Generates a runnable FastAPI + SQLAlchemy app skeleton from validated schemas.
"""
import json


def _db_type(col_type: str) -> str:
    mapping = {
        "string": "String(255)",
        "text": "Text",
        "integer": "Integer",
        "float": "Float",
        "boolean": "Boolean",
        "datetime": "DateTime",
    }
    return mapping.get(col_type.lower(), "String(255)")


def generate_models(db: dict) -> str:
    lines = [
        "from sqlalchemy import Column, Integer, String, Text, Float, Boolean, DateTime, ForeignKey",
        "from sqlalchemy.ext.declarative import declarative_base",
        "from datetime import datetime",
        "",
        "Base = declarative_base()",
        "",
    ]
    for table in db.get("tables", []):
        class_name = "".join(w.capitalize() for w in table["name"].split("_"))
        lines.append(f"class {class_name}(Base):")
        lines.append(f"    __tablename__ = '{table['name']}'")
        for col in table.get("columns", []):
            col_args = [_db_type(col["type"])]
            if col.get("primary_key"):
                col_args.append("primary_key=True")
            if col.get("foreign_key"):
                col_args.append(f"ForeignKey('{col['foreign_key']}')")
            nullable = "nullable=True" if col.get("nullable", True) else "nullable=False"
            col_args.append(nullable)
            if col.get("unique"):
                col_args.append("unique=True")
            args_str = ", ".join(col_args)
            lines.append(f"    {col['name']} = Column({args_str})")
        lines.append("")
    return "\n".join(lines)


def generate_routes(api: dict) -> str:
    lines = [
        "from fastapi import FastAPI, HTTPException, Depends",
        "from fastapi.middleware.cors import CORSMiddleware",
        "from pydantic import BaseModel",
        "from typing import Optional, List",
        "",
        "app = FastAPI(title='Generated App')",
        "app.add_middleware(CORSMiddleware, allow_origins=['*'], allow_methods=['*'], allow_headers=['*'])",
        "",
    ]
    for ep in api.get("endpoints", []):
        method = ep["method"].lower()
        path = ep["path"]
        func_name = path.replace("/", "_").replace("{", "").replace("}", "").strip("_")
        func_name = f"{method}_{func_name}" if func_name else f"{method}_root"
        lines.append(f"@app.{method}('{path}')")
        lines.append(f"def {func_name}():")
        lines.append(f"    # {ep.get('description', 'TODO: implement')}")
        lines.append(f"    return {{'message': 'TODO: implement {path}'}}")
        lines.append("")
    lines.append("if __name__ == '__main__':")
    lines.append("    import uvicorn")
    lines.append("    uvicorn.run(app, host='0.0.0.0', port=8000)")
    return "\n".join(lines)


def generate_env() -> str:
    return (
        "DATABASE_URL=sqlite:///./app.db\n"
        "SECRET_KEY=changeme\n"
        "ACCESS_TOKEN_EXPIRE_MINUTES=30\n"
    )


def run(db: dict, api: dict, intent: dict) -> dict:
    """Returns dict of filename → code content"""
    return {
        "models.py": generate_models(db),
        "main.py": generate_routes(api),
        ".env.example": generate_env(),
        "README.md": (
            f"# {intent.get('app_name', 'Generated App')}\n\n"
            "Auto-generated by AI Compiler\n\n"
            "## Setup\n"
            "```bash\npip install fastapi uvicorn sqlalchemy\npython main.py\n```\n"
        ),
    }
